In [2]:
import numpy as np


In [6]:
l = [1,2,3,4,5]
type(l)

list

In [7]:
t = (1,2,3,4,5)
type(t)

tuple

In [8]:
t1 = 1,2,3,4,5
type(t1)

tuple

In [9]:
t2 = 2,
type(t2)

tuple

In [12]:
l1 = []
l1

[]

In [16]:
arr1 = np.array(l1)
arr1

array([], dtype=float64)

In [17]:
mylist = [1,2,3,4,5]
print(mylist)
print(type(mylist))

[1, 2, 3, 4, 5]
<class 'list'>


In [19]:
t= tuple(mylist)
t

(1, 2, 3, 4, 5)

In [20]:
type(t)

tuple

In [21]:
mylist = [1,2,3,4,5]
a = np.array(mylist)
a

array([1, 2, 3, 4, 5])

In [26]:
type(a) #ndarray is number dimension array

numpy.ndarray

In [27]:
a

array([1, 2, 3, 4, 5])

In [28]:
a.ndim #number of dimension in the array

1

In [30]:
a.size # size of an array numebr of items

5

In [33]:
a.shape # shape of array

(5,)

# arrays

In [35]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [37]:
b = np.array(my_matrix)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
#array summery

In [39]:
print('The dimesion of array', b.ndim) #dimesion of array

The dimesion of array 2


In [42]:
print('the size of array', b.size) #size of array

the size of array 12


In [43]:
print('the shape of array',b.shape) #shape of array

the shape of array (3, 4)


In [45]:
print('data type of array', b.dtype) #data type of elements in the array

data type of array int32


In [46]:
print('type of structure', type(b))

type of structure <class 'numpy.ndarray'>


In [47]:
b.dtype

dtype('int32')

In [48]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr1.dtype

dtype('int32')

In [52]:
arr1.shape

(2, 2, 3)

In [54]:
arr1[0][1][2]

6

In [56]:
arr2 = np.array(["this", "is"])
arr2

array(['this', 'is'], dtype='<U4')

In [64]:
#reshape
arr3 = arr1.reshape((4,3))
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### arange

In [65]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
np.arange(2,15)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

In [68]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### linsspace

In [74]:
np.linspace(1,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [78]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [83]:
np.linspace(1,10,10, retstep = True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

### eye
##### create an identify matrix

In [12]:
np.eye(3) #generate 2d array of (5,5)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### brodcasting in an array

In [9]:
array_2d =np.array([[1,2,3,4,5],[6,7,8,9,10]])
scalar= 10
print(array_2d)

array = array_2d * scalar
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [14]:
l2 = [2,3,4,5,6]
l1 = l2*3
l1

[2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6]

In [16]:
a = np.array(l2)
b= a*3
b

array([ 6,  9, 12, 15, 18])

In [18]:
big_one = np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
big_one.dtype

dtype('float64')

In [20]:
big_one * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [21]:
bif_one = np.ones((3,4))
big_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
bigger_one = big_one*6-2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [23]:
bigger = np.array(big_one*3-0.4, dtype = 'int')
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [24]:
bigger.dtype

dtype('int32')

In [25]:
type(bigger)

numpy.ndarray

In [26]:
bigger.shape

(3, 4)

In [27]:
bigger.ndim

2

In [28]:
bigger/bigger

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
1/arr1

C:\Users\Pranali\AppData\Local\Temp\ipykernel_28400\393800717.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [33]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [34]:
arr+arr

array([0, 2, 4, 6])

In [35]:
arr

array([0, 1, 2, 3])

In [37]:
arr**arr

array([ 1,  1,  4, 27])

In [39]:
# use of copy function

In [43]:
l1 = [1,2,3,4,5,6]
l1

[1, 2, 3, 4, 5, 6]

In [52]:
l2 = l1 # shallow copy
l2

[1, 2, 10, 4, 5, 6]

In [53]:
l1[2]=10

In [54]:
l1

[1, 2, 10, 4, 5, 6]

In [55]:
l2

[1, 2, 10, 4, 5, 6]

In [56]:
# deep copy
l1 = [1,2,3,4,5,6]
l1

[1, 2, 3, 4, 5, 6]

In [62]:
l2 = l1.copy()   #deep copy

In [63]:
l2

[1, 2, 3, 100, 5, 6]

In [64]:
l1[3]= 100

In [65]:
l1

[1, 2, 3, 100, 5, 6]

In [66]:
l2

[1, 2, 3, 100, 5, 6]

### Random number generation

In [67]:
np.random.rand()

0.7819615427244675

In [68]:
np.random.rand(10)

array([0.78575662, 0.67413612, 0.04886372, 0.01034508, 0.5016408 ,
       0.35375729, 0.86064627, 0.90298902, 0.50354533, 0.77483341])

In [69]:
np.random.rand(3,4)

array([[0.74429469, 0.00875922, 0.21328706, 0.43782792],
       [0.19097207, 0.19664598, 0.30993656, 0.75838726],
       [0.16892623, 0.12839062, 0.22509251, 0.87572544]])

In [73]:
np.random.randn(5) #neg number

array([ 1.67188147, -1.12087425, -0.92363413,  1.41038665,  1.04442355])

In [85]:
np.random.randint(1,10)

6

In [87]:
arr1 = np.random.randn(10)
arr1

array([ 0.57949299, -0.43227841,  0.85188083, -2.42506274, -1.23687486,
       -0.31853964,  0.90881708, -0.21134523,  1.32545472,  0.89659212])

In [89]:
np.mean(arr1)

-0.006186313132887223

In [90]:
np.median(arr1)

0.1840738813083429

In [91]:
np.std(arr)

1.118033988749895

In [92]:
np.var(arr)

1.25

In [96]:
# rand int

In [98]:
arr2  = np.random.randint(1,100,10)
arr2

array([88, 83, 83, 65, 46, 75, 92, 74, 48, 52])

In [100]:
arr2.max()

92

In [101]:
arr2.min()

46

In [104]:
arr2.argmax() # gives max number index

6

In [106]:
arr2.argmin() # gives min number index

4

In [107]:
#*****************************************

In [115]:
l = [[2,5,8,9],[23,45,67,89],[14,14,17,18]]
arr = np.array(l)
arr

array([[ 2,  5,  8,  9],
       [23, 45, 67, 89],
       [14, 14, 17, 18]])

In [116]:
arr[2,3]

18

In [117]:
arr[2,2]

17

In [118]:
arr[0,2]

8

In [119]:
arr[:2,::2]

array([[ 2,  8],
       [23, 67]])

In [121]:
arr[1:3 ,1:3]

array([[45, 67],
       [14, 17]])

In [123]:
arr

array([[ 2,  5,  8,  9],
       [23, 45, 67, 89],
       [14, 14, 17, 18]])

In [124]:
arr[0]

array([2, 5, 8, 9])

In [126]:
arr[[1,0,2]]

array([[23, 45, 67, 89],
       [ 2,  5,  8,  9],
       [14, 14, 17, 18]])

In [128]:
arr[:,[1,3,0,2]]

array([[ 5,  9,  2,  8],
       [45, 89, 23, 67],
       [14, 18, 14, 17]])

### filtering

In [129]:
# filtering 

In [132]:
arr = np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [133]:
arr+100

array([ 101,  102, 1110,  104,  208,  118,  171,  710])

In [134]:
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [135]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [136]:
arr2=np.array([True,True,False,False,True])
arr2

array([ True,  True, False, False,  True])

In [137]:
np.where(arr2)

(array([0, 1, 4], dtype=int64),)

In [138]:
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [140]:
np.where(arr2<100)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [142]:
arr[[0,1,3,5,6]]

array([ 1,  2,  4, 18, 71])

In [143]:
arr[np.where(arr<100)]

array([ 1,  2,  4, 18, 71])

In [144]:
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [145]:
np.where(arr>100)

(array([2, 4, 7], dtype=int64),)

In [146]:
np.where(arr==100)

(array([], dtype=int64),)