In [1]:
import numpy as np

##### Create an array of 10 zeros

In [3]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##### Create an array of 10 ones

In [6]:
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


##### Create an array of 10 fives

In [13]:
fives = np.repeat(5,10)
fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

##### Create an array of the integers from 10 to 50

In [17]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

##### Create an array of all the even integers from 10 to 50

In [19]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

##### Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
arr = np.arange(9)
arr2 = arr.reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### Create a 3x3 identity matrix

In [31]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Use NumPy to generate a random number between 0 and 1

In [35]:
num = np.random.rand()
num

0.039732231841659305

##### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [51]:
arr = np.random.randn((25))
arr

array([ 1.91086743, -0.82021469, -1.45886602, -0.20565121,  0.39194817,
       -1.06205881,  2.75228406,  0.39891606, -0.60609768, -0.48439858,
       -0.73786981,  0.27409086,  0.25093035, -1.67152054, -2.00599621,
       -0.47156132,  0.79730809, -2.80544414,  1.22962767, -0.36754126,
        0.52414466, -0.21945318, -0.23182438, -0.33727215, -0.32795331])

##### Create the following matrix:
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [60]:
arr = np.linspace(0.01,1,100)
arr = arr.reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

##### Create an array of 20 linearly spaced points between 0 and 1:

In [62]:
arr = np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

##### Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:


In [63]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [65]:
result = mat[2:,1:]
print(result)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [67]:
result = mat[3,4]
result

20

In [71]:
result = mat[:3,1:2]
result

array([[ 2],
       [ 7],
       [12]])

In [72]:
result = mat[-1]
result

array([21, 22, 23, 24, 25])

In [74]:
result = mat[3:]
result

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### Get the sum of all the values in mat

In [77]:
sum = np.sum(mat)
sum

325

##### Get the standard deviation of the values in mat

In [79]:
std = np.std(mat)
std

7.211102550927978

##### Get the sum of all the columns in mat

In [80]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
sum = np.sum(mat, axis = 0)
sum

array([55, 60, 65, 70, 75])