In [1]:
import numpy as np

##### 1)how to create 1D Array ?

In [7]:
data = [1,2,3,4,5,6,7,8,9]
arr = np.array(data)
print(f'1D array is',arr)
type(arr)

1D array is [1 2 3 4 5 6 7 8 9]


numpy.ndarray

##### 2)How to create 2D Array ?

In [16]:
data = [[1,2,3,4],[5,6,7,8]]
arr = np.array(data)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


##### how to create 3D Array or ND Array ?

In [18]:
data = [[1,2,3,4],[5,6,7,8],[1,2,5,4]]
arr = np.array(data)
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 5 4]]


##### how to identified datatyp for numpy array?

In [22]:
arr
print(arr.dtype)

int32


##### Print 1D array with 5 zeros.

In [24]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


##### print zeros with 2 rows and 3 columns ?

In [26]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


##### Create array with eye() - diagonal values ?

In [43]:
arr = np.eye(5)
print(arr) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##### use of diag() square matrix ?

In [45]:
arr= np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


##### Print Range Between 1 To 15 and show 4 integers random numbers

In [56]:
l = np.random.randint(1,16,4) 
print(l)

[ 5  2 15 13]


##### describe the example of seed() function? and how to use it ? why seed()?

In [114]:
np.random.seed(12)
rand_arr4 = np.random.randint(1,100,20)
print("seed() showing same number only : ", rand_arr4)

seed() showing same number only :  [76 28  7  3  4 68 77 49 23 50 53  6 14 90 35 76 75  1 77 14]


In [115]:
np.random.seed(12)
arr = np.random.randint(1,100,20)
print(arr)

[76 28  7  3  4 68 77 49 23 50 53  6 14 90 35 76 75  1 77 14]


##### Print first position, last position and 2nd and 3rd position

In [119]:
num = np.array([1,2,3,4,5,6,7,8,9])
print(f'first position:- {num[0]} \n last poisition:- {num[-1]} \n 2nd position:- {num[1]} \n 3rd position:- {num[2]}')

first position:- 1 
 last poisition:- 9 
 2nd position:- 2 
 3rd position:- 3


##### if we don’t know last number of position how to show it by pragmatically?

In [121]:
num
print(f'last number is:- {num[-1]}')

last number is:- 9


##### create a matrix 3 * 3 with value ranging from 0 to 8

In [127]:
data = np.arange(0,9)
data = data.reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### create matrix 2 * 2 with value ranging from 1 to 3

In [133]:
arr = np.arange(0,4)
arr = arr.reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

##### create matrix 2 * 2 with value ranging from 1 to 4

In [135]:
arr1 = np.arange(1,5)
arr1 = arr1.reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

##### print random number from 0 to 1

In [144]:
random_num = np.random.rand()
random_num

0.6843250674615364

##### print size of num array

In [149]:
num = np.array([1,2,3,4,5,6,7,8,9,8,9,4,5,6,5,3,2,1,4,5])
print(num.size)

20


##### create an array of 20 linearly spaced point between 0 to 1

In [152]:
num = np.linspace(0,1,20)
num

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

##### Use of sort() function ?

In [156]:
arr= np.array([[1,2,3,4,5],[5,4,1,2,3],[9,7,5,4,8]])
print(np.sort(arr))

[[1 2 3 4 5]
 [1 2 3 4 5]
 [4 5 7 8 9]]


##### How to get the positions where elements of two arrays match?

In [160]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr2 = np.array([9,8,7,4,5,6,3,2,5])

print(arr[np.where(arr2==arr)])

[4 5 6]


##### Create a Numpy array filled with all zeros

In [165]:
zero = np.zeros(5)
zero

zero1 = np.zeros((2,3))
zero1

array([[0., 0., 0.],
       [0., 0., 0.]])

##### Check whether a Numpy array contains a specified row

In [179]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [178]:
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

True
False
False
True


##### Find the number of occurrences of a sequence in a NumPy array

In [180]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
arr

array([[2, 8, 9, 4],
       [9, 4, 9, 4],
       [4, 5, 9, 7],
       [2, 9, 4, 3]])

In [191]:
output = repr(arr).count('8')
output

1

##### Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [198]:
l1=[1,2,3,4,5,6,7,8,9]
arr = np.array(l1)
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

##### Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [202]:
arr = np.zeros(10)
arr[6] = 11
arr

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

##### Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [209]:
num = np.random.random((5,5))
num

array([[0.45130841, 0.40063163, 0.99513816, 0.17756418, 0.9625969 ],
       [0.41925027, 0.42405245, 0.46314887, 0.37372315, 0.4655081 ],
       [0.03516826, 0.08427267, 0.7325207 , 0.63619999, 0.02790779],
       [0.30017006, 0.22085252, 0.05501999, 0.52324607, 0.41636966],
       [0.04821875, 0.57240452, 0.80351665, 0.11360172, 0.27711721]])

In [213]:
print(np.min(num))
print(np.max(num))

0.027907788861532556
0.9951381603385585


##### Write a NumPy program to compute the multiplication of two given matrixes. Sample Matrix: [[1, 0], [0, 1]] [[1, 2], [3, 4]]

In [216]:
a = [[1, 0], [0, 1]]
b = [[1, 2], [3, 4]]

In [217]:
multi = np.dot(a,b)
multi

array([[1, 2],
       [3, 4]])

##### Create a two-dimensional array with the flattened input as a diagonal

In [223]:
ar1 = np.diagflat([[1,2,3],[4,5,6]])
ar1

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

##### Write a NumPy program to compute the sum of the diagonal element of a given array.

In [240]:
m = np.arange(25).reshape((5,5))
print("Original matrix:")
print(m)
print(np.trace(m))

Original matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
60
